CREATE TABLE COMMENTS (
                          ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                          POST_ID BIGINT NOT NULL,
                          PARENT_ID BIGINT,
                          CONTENTS VARCHAR(200) NOT NULL,
                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          FOREIGN KEY (POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE,
                          FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS(ID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE COMMENT_LIKES (
                               ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                               USER_ID BIGINT NOT NULL,
                               POST_ID BIGINT NOT NULL,
                               CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
                               FOREIGN KEY (POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE COMMENT_LIKES
    ADD CONSTRAINT UNIQUE_USER_POST
        UNIQUE (USER_ID, POST_ID);

